### ISSUE TITLE
Overflow of website text in infobox

### ISSUE THREAD

**Issue by DVRPCfreight** [dvrpc/MRP2045#12]
Consider setting overflow to hidden or force a break

![image](https://user-images.githubusercontent.com/8495073/30076316-7469e3fe-9246-11e7-8958-d4bfb0517e9f.png)

**Comment by crvanpollard** [comment]
Added the css below to fix this issue. Will close issue on next Pull Request
a, .one{
   /* These are technically the same, but use both */
  overflow-wrap: break-word;
  word-wrap: break-word;

  -ms-word-break: break-all;
  /* This is the dangerous one in WebKit, as it breaks things wherever */
  word-break: break-all;
  /* Instead use this non-standard one: */
  word-break: break-word;

  /* Adds a hyphen where the word breaks, if supported (No Blink) */
  -ms-hyphens: auto;
  -moz-hyphens: auto;
  -webkit-hyphens: auto;
  hyphens: auto;
}
