### ISSUE TITLE
Landing page not mobile friendly

### ISSUE THREAD

**Issue by DVRPCfreight** [dvrpc/MRP2045#20]
Formatting is all jacked up on mobile device.

![screenshot_20170905-145304](https://user-images.githubusercontent.com/8495073/30132719-5ebe7cf2-931f-11e7-9c67-f0e1500026b4.jpg)

**Comment by crvanpollard** [comment]
@DVRPCfreight please review now on Mobile to see if issues are still occur.
Survey button was removed and some media Queries were added a few commits back.

**Comment by DVRPCfreight** [comment]
Much better. Navbar still having an issue between 804px and 771px media width

**Comment by crvanpollard** [comment]
fixed
